### ISSUE TITLE
unix-route.c does not build on Lubuntu 26.04

### ISSUE THREAD

**Issue by fovea1959** [moshix/UnixNJE#13]
Description says it all:

```
gcc -c -g -O2 -Wall -Wno-comment -Wno-unknown-warning-option -Wno-format-truncation -Wno-format-overflow -Wno-stringop-truncation -DUSG -DNBCONNECT -DNBSTREAM -DUSE_XMIT_QUEUE -DUNIX -DUSE_SOCKOPT -DSOCKBUFSIZE=8192 -DUSE_ENUM_TYPES -DDEBUG -DCONFIG_FILE='"/etc/funetnje/funetnje.cf"' -DPID_FILE='"/run/funetnje.pid"' unix_route.c
unix_route.c: In function ‘open_route_file’:
unix_route.c:45:33: error: passing argument 3 of ‘bintree_open’ from incompatible pointer type [-Wincompatible-pointer-types]
   45 |                                 CompareRoute);
      |                                 ^~~~~~~~~~~~
      |                                 |
      |                                 int (*)(struct ROUTE_DATA *, struct ROUTE_DATA *)
In file included from unix_route.c:16:
bintree.h:49:88: note: expected ‘int (*)(void)’ but argument is of type ‘int (*)(struct ROUTE_DATA *, struct ROUTE_DATA *)’
   49 | extern struct Bintree *bintree_open __((const char *filename, const int eltsize, int (*eltcompare)()));
      |                                                                                  ~~~~~~^~~~~~~~~~~~~
prototypes.h:56:17: note: in definition of macro ‘__’
   56 | #  define __(x) x  /* With any STDC it is possible to check prototypes */
      |                 ^
unix_route.c:30:5: note: ‘CompareRoute’ declared here
   30 | int CompareRoute(struct ROUTE_DATA *r1, struct ROUTE_DATA *r2)
      |     ^~~~~~~~~~~~
At top level:
cc1: note: unrecognized command-line option ‘-Wno-unknown-warning-option’ may have been intended to silence earlier diagnostics
make: *** [Makefile:290: unix_route.o] Error 1
```

Problem is apparently due to change in gcc. Need to add `-Wno-error=incompatible-pointer-types` to Makefile.
